name: build

on:
  # allow to manual run the action
  workflow_dispatch: {}
  pull_request: {}
  merge_group: {}
  push:
    branches:
      - develop
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm build and test
        run: |
          npm run clean
          npm run build
          npm run test
      - run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          # renovate: datasource=docker depName=node
          node-version: "24"
      - name: "Build Package"
        run: |
          npm run clean
          npm run build

      - name: Test Container Image
        id: test-image
        run: |
          docker build -t continuoussecuritytooling/ajv-cli:${{github.run_number}} .
          wget https://gitlab.com/gitlab-org/gitlab/-/raw/master/ee/app/validators/json_schemas/security_orchestration_policy.json
          docker run -u 0 -v $(pwd):/build continuoussecuritytooling/ajv-cli:${{github.run_number}} migrate --spec=draft2020 -s /build/security_orchestration_policy.json
          docker run -u 0 -v $(pwd):/build continuoussecuritytooling/ajv-cli:${{github.run_number}} validate --spec=draft2020 --strict=false --validate-formats=true  -c ajv-formats --unicodeRegExp=false -s /build/security_orchestration_policy.json -d /build/test/gitlab/policy.yml

  build-results:
    name: Build results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
                || contains(needs.*.result, 'skipped')
                }}
